/* Additional record code for Interaction1 generated by the OpenModelica Compiler v1.26.0-dev-426-g7fcb459d2c-cmake. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Interaction1_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

