/* Simulation code for Modelica.Blocks.Examples.Interaction1 generated by the OpenModelica Compiler v1.26.0-dev-426-g7fcb459d2c-cmake. */
#if !defined(Interaction1__MODEL_H)
#define Interaction1__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Interaction1_functions.h"

#define Modelica_Blocks_Examples_Interaction1_booleanTable_isValidTable_index 0
#define Modelica_Blocks_Examples_Interaction1_integerTable_isValidTable_index 1
#define Modelica_Blocks_Examples_Interaction1_start_table_isValidTable_index 2
#define Modelica_Blocks_Examples_Interaction1_stop_table_isValidTable_index 3
#define Modelica_Blocks_Examples_Interaction1_timeTable_getInterpolationCoefficients_index 4
#define Modelica_Blocks_Tables_Internal_getNextTimeEvent_index 5
#define Modelica_Blocks_Tables_Internal_getTimeTableTmax_index 6
#define Modelica_Blocks_Tables_Internal_getTimeTableTmin_index 7
#define Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer_index 8
#define Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index 9
#define Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_index 10

extern void Interaction1_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Interaction1_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Interaction1_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Interaction1_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Interaction1_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Interaction1_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Interaction1_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Interaction1_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Interaction1_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Interaction1_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Interaction1_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Interaction1_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Interaction1_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Interaction1_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Interaction1_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Interaction1_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Interaction1_relationDescription(int i);
extern void Interaction1_function_initSample(DATA *data, threadData_t *threadData);
extern int Interaction1_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int Interaction1_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int Interaction1_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int Interaction1_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int Interaction1_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int Interaction1_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int Interaction1_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int Interaction1_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int Interaction1_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int Interaction1_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int Interaction1_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int Interaction1_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int Interaction1_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int Interaction1_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* Interaction1_linear_model_frame(void);
extern const char* Interaction1_linear_model_datarecovery_frame(void);
extern int Interaction1_mayer(DATA* data, modelica_real** res, short *);
extern int Interaction1_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Interaction1_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int Interaction1_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Interaction1_setInputData(DATA *data, const modelica_boolean file);
extern int Interaction1_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Interaction1_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Interaction1_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Interaction1_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Interaction1_read_simulation_info(SIMULATION_INFO* simulationData);
extern void Interaction1_read_input_fmu(MODEL_DATA* modelData);
extern void Interaction1_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Interaction1_inputNames(DATA* data, char ** names);
extern int Interaction1_dataReconciliationInputNames(DATA* data, char ** names);
extern int Interaction1_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int Interaction1_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Interaction1_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Interaction1_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Interaction1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Interaction1__MODEL_H) */


