# Toolchain for 64-bit Linux
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Compiler
set(CMAKE_C_COMPILER gcc)
set(CMAKE_C_FLAGS "-m64" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_CXX_FLAGS "-m64" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-m64" CACHE STRING "" FORCE)

# Where to find target environment
set(CMAKE_FIND_ROOT_PATH /usr /usr/lib/x86_64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
